-- begin CUSTOMFILTER_CUSTOM_FILTER
alter table CUSTOMFILTER_CUSTOM_FILTER add constraint FK_CUSTOMFILTER_CUSTOM_FILTER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_CUSTOMFILTER_CUSTOM_FILTER_ON_USER on CUSTOMFILTER_CUSTOM_FILTER (USER_ID)^

-- end CUSTOMFILTER_CUSTOM_FILTER
