-- begin COMMONSERVICES_GROOVY_FILTER
alter table COMMONSERVICES_GROOVY_FILTER add constraint FK_COMMONSERVICES_GROOVY_FILTER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_COMMONSERVICES_GROOVY_FILTER_ON_USER on COMMONSERVICES_GROOVY_FILTER (USER_ID)^

-- end COMMONSERVICES_GROOVY_FILTER
-- begin COMMONSERVICES_GROOVY_FILTER_GROUP_LINK
alter table COMMONSERVICES_GROOVY_FILTER_GROUP_LINK add constraint FK_COMGROFILGRO_ON_GROOVY_FILTER foreign key (GROOVY_FILTER_ID) references COMMONSERVICES_GROOVY_FILTER(ID)^
alter table COMMONSERVICES_GROOVY_FILTER_GROUP_LINK add constraint FK_COMGROFILGRO_ON_GROUP foreign key (GROUP_ID) references SEC_GROUP(ID)^
-- end COMMONSERVICES_GROOVY_FILTER_GROUP_LINK
