-- begin TESTCUBA_FORNITORE
alter table TESTCUBA_FORNITORE add constraint FK_TESTCUBA_FORNITORE_ON_COMUNE foreign key (COMUNE_ID) references TESTCUBA_COMUNE(ID)^
create index IDX_TESTCUBA_FORNITORE_ON_COMUNE on TESTCUBA_FORNITORE (COMUNE_ID)^
-- end TESTCUBA_FORNITORE
-- begin TESTCUBA_ORDINE_T
alter table TESTCUBA_ORDINE_T add constraint FK_TESTCUBA_ORDINE_T_ON_CLIENTE foreign key (CLIENTE_ID) references TESTCUBA_CLIENTE(ID)^
create index IDX_TESTCUBA_ORDINE_T_ON_CLIENTE on TESTCUBA_ORDINE_T (CLIENTE_ID)^
-- end TESTCUBA_ORDINE_T
-- begin TESTCUBA_PRODOTTO
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_UNITA_MISURA foreign key (UNITA_MISURA_ID) references TESTCUBA_UNITA_MISURA(ID)^
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_PIANO_CONTO foreign key (PIANO_CONTO_ID) references TESTCUBA_PIANO_CONTO(ID)^
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF foreign key (MAGAZZINO_DEF_ID) references TESTCUBA_MAGAZZINO(ID)^
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_FORNITORE_DEFAULT foreign key (FORNITORE_DEFAULT_ID) references TESTCUBA_FORNITORE(ID)^
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_CATEGORIA_GESTIONALE foreign key (CATEGORIA_GESTIONALE_ID) references TESTCUBA_CATEGORIA_GESTIONALE(ID)^
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_CATEGORIA_TECNOLOGICA foreign key (CATEGORIA_TECNOLOGICA_ID) references TESTCUBA_CATEGORIA_TECNOLOGICA(ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_UNITA_MISURA on TESTCUBA_PRODOTTO (UNITA_MISURA_ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_PIANO_CONTO on TESTCUBA_PRODOTTO (PIANO_CONTO_ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF on TESTCUBA_PRODOTTO (MAGAZZINO_DEF_ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_FORNITORE_DEFAULT on TESTCUBA_PRODOTTO (FORNITORE_DEFAULT_ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_CATEGORIA_GESTIONALE on TESTCUBA_PRODOTTO (CATEGORIA_GESTIONALE_ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_CATEGORIA_TECNOLOGICA on TESTCUBA_PRODOTTO (CATEGORIA_TECNOLOGICA_ID)^
-- end TESTCUBA_PRODOTTO
-- begin TESTCUBA_CLIENTE
alter table TESTCUBA_CLIENTE add constraint FK_TESTCUBA_CLIENTE_ON_COMUNE foreign key (COMUNE_ID) references TESTCUBA_COMUNE(ID)^
create index IDX_TESTCUBA_CLIENTE_ON_COMUNE on TESTCUBA_CLIENTE (COMUNE_ID)^
-- end TESTCUBA_CLIENTE
-- begin TESTCUBA_ORDINE_D
alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_PRODOTTO foreign key (PRODOTTO_ID) references TESTCUBA_PRODOTTO(ID)^
alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_ORDINE foreign key (ORDINE_ID) references TESTCUBA_ORDINE_T(ID)^
create index IDX_TESTCUBA_ORDINE_D_ON_PRODOTTO on TESTCUBA_ORDINE_D (PRODOTTO_ID)^
create index IDX_TESTCUBA_ORDINE_D_ON_ORDINE on TESTCUBA_ORDINE_D (ORDINE_ID)^
-- end TESTCUBA_ORDINE_D
-- begin TESTCUBA_MOV_MAG
alter table TESTCUBA_MOV_MAG add constraint FK_TESTCUBA_MOV_MAG_ON_PRODOTTO foreign key (PRODOTTO_ID) references TESTCUBA_PRODOTTO(ID)^
create index IDX_TESTCUBA_MOV_MAG_ON_PRODOTTO on TESTCUBA_MOV_MAG (PRODOTTO_ID)^
create index IDX_TESTCUBA_MOV_MAG on TESTCUBA_MOV_MAG (PRODOTTO_ID) ^
-- end TESTCUBA_MOV_MAG
