alter table COMMONSERVICES_GROOVY_FILTER add constraint FK_COMMONSERVICES_GROOVY_FILTER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_COMMONSERVICES_GROOVY_FILTER_ON_USER on COMMONSERVICES_GROOVY_FILTER (USER_ID);
