alter table TESTCUBA_CLIENTE add constraint FK_TESTCUBA_CLIENTE_ON_COMUNE foreign key (COMUNE_ID) references TESTCUBA_COMUNE(ID);
create index IDX_TESTCUBA_CLIENTE_ON_COMUNE on TESTCUBA_CLIENTE (COMUNE_ID);
