alter table TESTCUBA_MOV_MAG add constraint FK_TESTCUBA_MOV_MAG_ON_PRODOTTO foreign key (PRODOTTO_ID) references TESTCUBA_PRODOTTO(ID);
create index IDX_TESTCUBA_MOV_MAG_ON_PRODOTTO on TESTCUBA_MOV_MAG (PRODOTTO_ID);
