alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_PRODOTTO foreign key (PRODOTTO_ID) references TESTCUBA_PRODOTTO(ID);
alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_ORDINE foreign key (ORDINE_ID) references TESTCUBA_ORDINE_T(ID);
create index IDX_TESTCUBA_ORDINE_D_ON_PRODOTTO on TESTCUBA_ORDINE_D (PRODOTTO_ID);
create index IDX_TESTCUBA_ORDINE_D_ON_ORDINE on TESTCUBA_ORDINE_D (ORDINE_ID);
