alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF foreign key (MAGAZZINO_DEF_ID) references TESTCUBA_MAGAZZINO(ID);
create index IDX_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF on TESTCUBA_PRODOTTO (MAGAZZINO_DEF_ID);
