-- begin TESTCUBA_ORDINE_T
alter table TESTCUBA_ORDINE_T add constraint FK_TESTCUBA_ORDINE_T_ON_CLIENTE foreign key (CLIENTE_ID) references TESTCUBA_CLIENTE(ID)^
create index IDX_TESTCUBA_ORDINE_T_ON_CLIENTE on TESTCUBA_ORDINE_T (CLIENTE_ID)^
-- end TESTCUBA_ORDINE_T
-- begin TESTCUBA_PRODOTTO
alter table TESTCUBA_PRODOTTO add constraint FK_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF foreign key (MAGAZZINO_DEF_ID) references TESTCUBA_MAGAZZINO(ID)^
create index IDX_TESTCUBA_PRODOTTO_ON_MAGAZZINO_DEF on TESTCUBA_PRODOTTO (MAGAZZINO_DEF_ID)^
-- end TESTCUBA_PRODOTTO
-- begin TESTCUBA_CLIENTE
alter table TESTCUBA_CLIENTE add constraint FK_TESTCUBA_CLIENTE_ON_COMUNE foreign key (COMUNE_ID) references TESTCUBA_COMUNE(ID)^
create index IDX_TESTCUBA_CLIENTE_ON_COMUNE on TESTCUBA_CLIENTE (COMUNE_ID)^
-- end TESTCUBA_CLIENTE
-- begin TESTCUBA_ORDINE_D
alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_PRODOTTO foreign key (PRODOTTO_ID) references TESTCUBA_PRODOTTO(ID)^
alter table TESTCUBA_ORDINE_D add constraint FK_TESTCUBA_ORDINE_D_ON_ORDINE foreign key (ORDINE_ID) references TESTCUBA_ORDINE_T(ID)^
create index IDX_TESTCUBA_ORDINE_D_ON_PRODOTTO on TESTCUBA_ORDINE_D (PRODOTTO_ID)^
create index IDX_TESTCUBA_ORDINE_D_ON_ORDINE on TESTCUBA_ORDINE_D (ORDINE_ID)^
-- end TESTCUBA_ORDINE_D
